---
services:
  dockersocket:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/docker-socket-proxy-local:${TAG?}
    build:
      context: ${CURDIR}/src/
      dockerfile: ./images/docker-socket-proxy/Dockerfile
      target: local
      args:
        - SOCKET_PROXY_VERSION=${SOCKET_PROXY_VERSION?}

  traefik:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/traefik-local:${TAG?}
    build:
      context: ${CURDIR}/src/
      dockerfile: ./images/traefik/Dockerfile
      target: local
      args:
        - TIMEZONE=${TIMEZONE?}
        - TRAEFIK_VERSION=${TRAEFIK_VERSION?}
        - TRAEFIK_DOMAIN_NAME=${TRAEFIK_DOMAIN_NAME?}
        - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL?}
        - TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER_EMAIL=${TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER_EMAIL?}
        - TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER_TOKEN=${TRAEFIK_ACME_DNS_CHALLENGE_PROVIDER_TOKEN?}
        - TRAEFIK_DASHBOARD=${TRAEFIK_DASHBOARD?}
        - TRAEFIK_DASHBOARD_SUBDOMAIN=${TRAEFIK_DASHBOARD_SUBDOMAIN?}
        - TRAEFIK_BASIC_AUTH_USERNAME=${TRAEFIK_BASIC_AUTH_USERNAME?}
        - TRAEFIK_BASIC_AUTH_PASSWORD_HASH=${TRAEFIK_BASIC_AUTH_PASSWORD_HASH?}
        - TRAEFIK_MID_RATE_LIMIT_AVERAGE=${TRAEFIK_MID_RATE_LIMIT_AVERAGE?}
        - TRAEFIK_MID_RATE_LIMIT_BURST=${TRAEFIK_MID_RATE_LIMIT_BURST?}
        - TRAEFIK_MID_SEC_CUST_RESPONSE_X_ROBOTS_TAG=${TRAEFIK_MID_SEC_CUST_RESPONSE_X_ROBOTS_TAG?}
        - TRAEFIK_MID_SEC_CUST_RESPONSE_X_FORWARDED_SERVER=${TRAEFIK_MID_SEC_CUST_RESPONSE_X_FORWARDED_SERVER?}
        - TRAEFIK_MID_SEC_CUST_RESPONSE_X_FORWARDED_PROTO=${TRAEFIK_MID_SEC_CUST_RESPONSE_X_FORWARDED_PROTO?}
        - TRAEFIK_MID_SEC_CUST_REQUEST_X_FORWARDED_PROTO=${TRAEFIK_MID_SEC_CUST_REQUEST_X_FORWARDED_PROTO?}
        - TRAEFIK_MID_SEC_CUST_SSL_PROXY_X_FORWARDED_PROTO=${TRAEFIK_MID_SEC_CUST_SSL_PROXY_X_FORWARDED_PROTO?}
        - TRAEFIK_MID_SEC_HOSTS_PROXY=${TRAEFIK_MID_SEC_HOSTS_PROXY?}
        - TRAEFIK_MID_SEC_REFERRER_POLICY=${TRAEFIK_MID_SEC_REFERRER_POLICY?}
        - TRAEFIK_MID_SEC_CONTENT_TYPE_NO_SNIFF=${TRAEFIK_MID_SEC_CONTENT_TYPE_NO_SNIFF?}
        - TRAEFIK_MID_SEC_BROWSER_XSS_FILTER=${TRAEFIK_MID_SEC_BROWSER_XSS_FILTER?}
        - TRAEFIK_MID_SEC_FORCE_STS_HEADER=${TRAEFIK_MID_SEC_FORCE_STS_HEADER?}
        - TRAEFIK_MID_SEC_STS_INCLUDE_SUBDOMAIN=${TRAEFIK_MID_SEC_STS_INCLUDE_SUBDOMAIN?}
        - TRAEFIK_MID_SEC_STS_SECONDS=${TRAEFIK_MID_SEC_STS_SECONDS?}
        - TRAEFIK_MID_SEC_STS_PRELOAD=${TRAEFIK_MID_SEC_STS_PRELOAD?}
        - TRAEFIK_MID_SEC_FRAME_DENY=${TRAEFIK_MID_SEC_FRAME_DENY?}
        - TRAEFIK_MID_SEC_CONTENT_SECURITY_POLICY=${TRAEFIK_MID_SEC_CONTENT_SECURITY_POLICY?}
        - TRAEFIK_MID_SEC_PERMISSION_POLICY=${TRAEFIK_MID_SEC_PERMISSION_POLICY?}
        - TRAEFIK_MID_CORS_ALLOW_CREDENTIALS=${TRAEFIK_MID_CORS_ALLOW_CREDENTIALS?}
        - TRAEFIK_MID_CORS_ALLOW_HEADERS=${TRAEFIK_MID_CORS_ALLOW_HEADERS?}
        - TRAEFIK_MID_CORS_ALLOW_METHODS=${TRAEFIK_MID_CORS_ALLOW_METHODS?}
        - TRAEFIK_MID_CORS_ALLOW_ORIGIN_LIST=${TRAEFIK_MID_CORS_ALLOW_ORIGIN_LIST?}
        - TRAEFIK_MID_CORS_MAX_AGE=${TRAEFIK_MID_CORS_MAX_AGE?}
        - TRAEFIK_MID_CORS_ADD_VERY_HEADER=${TRAEFIK_MID_CORS_ADD_VERY_HEADER?}
        - TRAEFIK_MID_RESPONSE_CACHE_CONTROL=${TRAEFIK_MID_RESPONSE_CACHE_CONTROL?}
        - TRAEFIK_MID_COMPRESS=${TRAEFIK_MID_COMPRESS?}

  logger:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/logger-local:${TAG?}
    build:
      context: ${CURDIR}/src/
      dockerfile: ./images/logger/Dockerfile
      target: local
      args:
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - TIMEZONE=${TIMEZONE?}
